
.section .vectors

_vectors:
          .long    0x000FFFF0                   /*0x00000000*//* Pilha no topo real da RAM (ajuste se seu limite for outro) */
          .long    _start                       /*0x00000004*/
          .long    0x00080008      /*SvcBusError           0x0008*/
          .long    0x0008000c      /*Svcaddress_err        0x000C*/
          .long    0x00080010      /*SvcIllegalIns         0x0010*/
          .long    0x00080014      /*SvcDiv0_handler       0x0014*/
          .long    0x00080018      /*SvcChkIns             0x0018*/
          .long    0x0008001e      /*SvcTrapvIns           0x001c*/
          .long    0x00080024      /*SvcPrivViolation      0x0020*/
          .long    0x0008002a      /*SvcTrace              0x0024*/
          .long    0x00080030      /*SvcLineA              0x0028*/
          .long    0x00080036      /*SvcLineF              0x002c*/
          .long    0x0008003c      /*bad_exception         0x0030*/
          .long    0x00080042      /*bad_exception         0x0034*/
          .long    0x00080048      /*bad_exception         0x0038*/
          .long    0x0008004e      /*bad_exception         0x003c*/
          .long    0x00080054      /*bad_exception         0x0040*/
          .long    0x0008005a      /*bad_exception         0x0044*/
          .long    0x00080060      /*bad_exception         0x0048*/
          .long    0x00080066      /*bad_exception         0x004c*/
          .long    0x0008006c      /*bad_exception         0x0050*/
          .long    0x00080072      /*bad_exception         0x0054*/
          .long    0x00080078      /*bad_exception         0x0058*/
          .long    0x0008007e      /*bad_exception         0x005c*/
          .long    0x00080084      /*SpuriousHandler       0x0060*/
          .long    0x0008008a      /*Int1Handler           0x0064*/
          .long    0x00080090      /*Int2Handler           0x0068*/
          .long    Int3Handler     /*0x00080096*/      /*Int3Handler           0x006c*/
          .long    0x0008009c      /*Int4Handler           0x0070*/
          .long    0x000800a2      /*Int5Handler           0x0074*/
          .long    0x000800a8      /*Int6Handler           0x0078*/
          .long    0x000800ae      /*Int7Handler           0x007c*/
          .long    0x000800b4      /*Trap0Handler          0x0080*/
          .long    0x000800ba      /*Trap1Handler          0x0084*/
          .long    0x000800c0      /*Trap2Handler          0x0088*/
          .long    0x000800c6      /*Trap3Handler          0x008c*/
          .long    0x000800cc      /*Trap4Handler          0x0090*/
          .long    0x000800d2      /*Trap5Handler          0x0094*/
          .long    0x000800d8      /*Trap6Handler          0x0098*/
          .long    0x000800de      /*Trap7Handler          0x009c*/
          .long    0x000800e4      /*Trap8Handler          0x00a0*/
          .long    0x000800ea      /*Trap9Handler          0x00a4*/
          .long    0x000800f0      /*TrapAHandler          0x00a8*/
          .long    0x000800f6      /*TrapBHandler          0x00ac*/
          .long    0x000800fc      /*TrapCHandler          0x00b0*/
          .long    0x00080102      /*TrapDHandler          0x00b4*/
          .long    0x00080108      /*TrapEHandler          0x00b8*/
          .long    0x0008010e      /*TrapFHandler          0x00bc*/

          .rept    207
          .long    DefaultHandler
          .endr

.section .text

.global _start
.global _delay_ms
.global printString
.global UartWriteCh

.extern duart_send_char
.extern build_jump_table
.extern sys_setramvector
.extern Trap1Handler
.extern sys_setramvector

.equ WR_CHAR, 0xFF912B
.equ DUART_BASE, 0x00FF9000

_start:
        ORI.W   #0x0700,%SR         /* Desabilita interrupções no boot */
        LEA     0x000FFFF0,%A7      /* Garante o ponteiro da pilha limpo */

        MOVE.L  #3,%D1        /* espera 5 segundos */
        JSR     delay_seconds

        MOVE.B  #'1',WR_CHAR
/*
; Busca de RAM para m68k (Orion68)
; Retorna em A0 o endereço onde a RAM termina.
*/
/************************************************************************************* */
/* Find the total of SRAM */
FIND_RAM:
    MOVE.L  #0x00080000,%A0    /*; A0 = Endereço inicial da busca (Ajuste para o seu mapa)*/
    MOVE.L  #0x55AA55AA,%D1    /*; D1 = Padrão de teste (alternando 0s e 1s)*/
    MOVE.L  #0x00000400,%D2    /*; D2 = Incremento de salto (ex: 1KB)*/

    MOVE.B  #'2',WR_CHAR

.busca_loop:
    ADD.L   %D2,%A0            /*; Avança o ponteiro de memória*/
    MOVE.L  (%A0),%D0          /*; Salva o dado original da memória no D0*/
    MOVE.L  %D1,(%A0)          /*; Escreve o padrão de teste na RAM*/

    CMP.L   (%A0),%D1          /*; Lê da RAM e compara com o padrão*/
    BNE.S   .fim_ram          /*; Se não for igual (não há RAM), sai do loop*/

    MOVE.L  %D0,(%A0)          /*; Restaura o dado original (é RAM válida)*/
    BRA.S   .busca_loop       /*; Repete para o próximo bloco*/

    MOVE.B  #'3',WR_CHAR

.fim_ram:
        /*; A0 contém o endereço do fim da RAM.*/
        MOVE.L  %A0,%A4
        /*; A4 contém o endereço do fim da RAM.*/

    MOVE.B  #'4',WR_CHAR

/********************************************/
/* Clear the entire SRAM */
        /* 1. Limpa a RAM (bss) */
        LEA     0x080000,%A0
        MOVE.L  %A4,%A1
        MOVE.L  #0x0,%D0
.ClearLoop:
        MOVE.L  %D0,(%A0)+
        CMPA.L  %A0,%A1
        BHI     .ClearLoop

        LEA     0x080600,%A0
        MOVE.L  %A4,(%A0)

        MOVE.B  #'5',WR_CHAR

/*        MOVE.L  %A4,%D0
//        ANDI.L  #0xFFFFFFFC,%D0
//        MOVE.L  %D0,%A7
*/
    MOVE.B  #'6',WR_CHAR

/********************************************/
/* 2. Carrega seção .data da ROM para a RAM */
        lea     __data_load_start, %A0
        lea     __data_start, %A1
        lea     __data_end, %A2
copy_data:
        cmpa.l  %A2, %A1
        bge.s   go_ahead
        move.b  (%A0)+, (%A1)+
        bra.s   copy_data
go_ahead:

        MOVE.B  #'7',WR_CHAR

        /* Duart A init */
        // DUART_ACR = 0x00; (seleciona baud Set 1)
        move.b #0x00, (DUART_BASE + 0x09).l
        // DUART_SRA_CSRA = 0xCC; (Rx/Tx = 38400 baud, cristal 3.6864MHz)
        move.b #0xCC, (DUART_BASE + 0x03).l
        // DUART_CRA = 0x10; (reseta ponteiro MR -> aponta p/ MR1A)
        move.b #0x10, (DUART_BASE + 0x05).l
        // DUART_MR1A_MR2A = 0x13; (MR1A: 8 bits, sem paridade, char mode)
        move.b #0x13, (DUART_BASE + 0x01).l
        // DUART_MR1A_MR2A = 0x07; (MR2A: modo normal, 1 stop bit)
        move.b #0x07, (DUART_BASE + 0x01).l
        // DUART_CRA = 0x20; (reset receiver)
        move.b #0x20, (DUART_BASE + 0x05).l
        // DUART_CRA = 0x30; (reset transmitter)
        move.b #0x30, (DUART_BASE + 0x05).l
        // DUART_CRA = 0x05; (habilita Rx e Tx)
        move.b #0x05, (DUART_BASE + 0x05).l

        MOVE.B  #'8',WR_CHAR

        lea     bootstrap_string,%a0
        jsr     print_string

        MOVE.B  #'9',WR_CHAR

        /*Para empilhar os parametros de uma função
          começamos do ultimo para o primeiro.
          e no retorno da função temos que somar (4 * total de parâmetros) no SP.      
        */        
        | 1. Empilha o último argumento (count)
        move.l  #50, -(%SP)            /*#254, -(%SP)*/
        | 2. Empilha o segundo argumento (target_addr)
        move.l  DefaultHandler, -(%SP)
        | 3. Empilha o primeiro argumento (base_addr)
        move.l  #0x00080000, -(%SP)
        | Chama a função C
        BSR     build_jump_table
        | Limpa a pilha após o retorno (3 argumentos * 4 bytes = 12 bytes)
        ADDA.L  #12, %SP

        MOVE.B  #'7',WR_CHAR

        move.l  #Int2Handler, -(%SP)     | handler_addr = OS_TickISR (empilhado 1o, e' o ultimo parametro)
        move.l  #0x00080090, -(%SP)      | stub_addr = 0x00080090 (empilhado 2o, e' o 1o parametro)
        BSR     sys_setramvector           | Chama a função C
        ADDA.L  #8, %SP                  | 2 argumentos * 4 bytes = 8 (o comentario diz "3 argumentos", mas a conta certa e' 2)

        move.l  #5,%D1
        BSR     delay_seconds
        MOVE.B  #'8',WR_CHAR

        move.l  #Trap1Handler, -(%SP)     | handler_addr = trap1_handler (empilhado 1o, e' o ultimo parametro)
        move.l  #0x000800ba, -(%SP)      | stub_addr = 0x000800ba (empilhado 2o, e' o 1o parametro)
        BSR     sys_setramvector           | Chama a função C
        ADDA.L  #8, %SP                  | 2 argumentos * 4 bytes = 8 (o comentario diz "3 argumentos", mas a conta certa e' 2)

        move.l  #5,%D1
        BSR     delay_seconds
        MOVE.B  #'8',WR_CHAR


        move.l  #TrapCHandler, -(%SP)     | handler_addr = TrapCHandler (empilhado 1o, e' o ultimo parametro)
        move.l  #0x000800fc, -(%SP)      | stub_addr = 0x000800fc (empilhado 2o, e' o 1o parametro)
        BSR     sys_setramvector           | Chama a função C
        ADDA.L  #8, %SP                  | 2 argumentos * 4 bytes = 8 (o comentario diz "3 argumentos", mas a conta certa e' 2)

        move.l  #5,%D1
        BSR     delay_seconds
        MOVE.B  #'8',WR_CHAR





        lea     interrupt_status,%a0
        jsr     print_string
        andi.w #0xF8FF,%SR

        jsr     main

.dead:
        bra.s   .dead


PicoWrCh:
        LEA     0x00FF8001,%A1
        MOVE.B  %D0,(%A1)
        NOP
        NOP
        NOP
        NOP
        RTS

printString:
        MOVE.L  4(%A7),%A0     /* pega o 1º argumento da pilha (ponteiro da string) e põe em A0 */
        MOVE.L  %A0,-(%A7)     /* preserva A0 original do chamador (é caller-saved, mas por segurança) */
        ADDQ.L  #4,%A7
print_string:
        move.b  (%A0)+,%d0
        beq     .end_print_string
        jsr     duart_send_char
        /*jsr     PicoWrCh*/
        bra     print_string
.end_print_string:
        RTS

startup_delay:
        move.l  #2000,%d1
.outer_loop:
        move.l  #400,%d2
.inner_loop:
        subq.l  #1,%d2
        bne     .inner_loop
        subq.l  #1,%d1
        bne     .outer_loop
        rts
/*
; ---------------------------------------------------------
; DELAY_1MS: Gera um atraso de aproximadamente 1 ms
; Frequência da CPU: 16 MHz (Período do clock = 62.5 ns)
; ---------------------------------------------------------
*/
_delay_ms:
    MOVE.L  %D0, -(%A7)
    MOVE.L  #1333,%D0
.loop1:
    DBRA    %D0, .loop1

    MOVE.L  (%A7)+,%D0
    RTS
/*
; ---------------------------------------------------------
; DELAY_1MS_8MHZ: Gera um atraso de aproximadamente 1 ms
; Frequência da CPU: 8 MHz (Período do clock = 125 ns)
; ---------------------------------------------------------
*/
DELAY_1MS_8MHZ:
    MOVE.L  %D0,-(%A7)
    MOVE.L  #666,%D0
.loop2:
    DBRA    %D0, .loop2
    MOVE.L  (%A7)+,%D0
    RTS
/*
; ---------------------------------------------------------
; DELAY_1MS_4MHZ: Gera um atraso de aproximadamente 1 ms
; Frequência da CPU: 4 MHz (Período do clock = 250 ns)
; ---------------------------------------------------------
*/
DELAY_1MS_4MHZ:
    MOVE.L  %D0,-(%A7)
    MOVE.L  #333,%D0
.loop3:
    DBRA    %D0, .loop3
    MOVE.L  (%A7)+,%D0
    RTS

/*
; ---------------------------------------------------------
; DELAY_SECONDS: Gera um atraso de N segundos
; Entrada: D1 = número de segundos (0 = retorna imediatamente)
; Usa _delay_ms internamente (assume 16MHz, ajuste se mudar clock)
; ---------------------------------------------------------
*/
delay_seconds:
        MOVE.L  %D0,-(%A7)
        MOVE.L  %D1,-(%A7)

        TST.L   %D1
        BEQ     .delay_seconds_done   /* se pediram 0 segundos, sai direto */

.loop_outer:
        MOVE.L  #550,%D0             /* 1000 x 1ms = 1 segundo */
.loop_inner:
        JSR     DELAY_1MS_8MHZ
        SUBQ.L  #1,%D0
        BNE     .loop_inner

        SUBQ.L  #1,%D1
        BNE     .loop_outer

.delay_seconds_done:
        MOVE.L  (%A7)+,%D1
        MOVE.L  (%A7)+,%D0
        RTS

DefaultHandler:
        rte

.section .text
.align 2
bootstrap_string:
        .byte   13, 10
        .ascii  "PDS317 - Bootstrap 2026 V1.0"
        .byte   13, 10, 0
interrupt_status:
        .ascii  "Bootstrap interrupt on"
        .byte   13, 10, 0

.align 2        /* <--- CRÍTICO: Garante que o PRÓXIMO arquivo linkado comece em endereço PAR */

/*
        MEMORY ADDRESS

0x00000000      TO      0x00000002      =       RESET VECTOR
0x00000004      TO      0x0000003E      =       INTERRUPT VECTORS
0x00000040      TO      0x0000007E      =       TRAP VECTORS

*/
/*        MOVE.L %A4,0x80000*/
        /*; 2. Alinha o endereço (Garante que é múltiplo de 4)*/
        /*; Se A0 terminar em um endereço ímpar ou não alinhado a 32 bits,*/
        /*; esta operação arredonda o valor para baixo (área segura da RAM).*/
/*        MOVE.L  %A4,%D0 */
/*        ANDI.L  #0xFFFFFFFC,%D0*/    /*; Limpa os 2 bits menos significativos (alinha a 4 bytes)*/
/*        MOVE.L  %D0,%A7 */           /*; Seta o Stack Pointer (A7 / SP) com o valor seguro*/
