# AmigaOS/68k

TARGET = _os3
TARGETEXTENSION = 

CC = vc +aos68k
CCOUT = -o=
CFLAGS = -c -ffreestanding -nostdlib -DNO_FLOAT -D__mc68000__ -m68000 -cpu=68000 -merge-strings -DAMIGA $(OUTFMTS) -O1

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -nostdlib -lmieee -L../../../lib

RM = delete force quiet

include make.rules
